### ISSUE TITLE
rf.running always false

### ISSUE THREAD

**Issue by pepesrz91** [mzareei/TC4003_assignment_Group_7#7]
Que hay team! 

## Problema
Espero que todos bien levanto este issue porque al estar trabajando en la nueva parte del assignment nunca llegaba al AppendEntriesHandler. 

Creo que la razón por la que no lograba llegar es porque la propiedad ```rf.running``` siempre llega como __false__ en en la función ```PromoteToLeadert()```. 

```golang

func (rf *Raft) PromoteToLeader() {
	for range rf.heartBeatTicker.C {   // deliver clock ticks at intervals
		if !rf.running ||rf.role != 2 {
			break
		}
		heartbeat := rf.craftHeartBeatMessage()//Upon election: send initial empty AppendEntries RPCs (heartbeat) to each server
		for peerId := range rf.peers{
			if peerId  != rf.me {
				go func(peer int) {
					rf.mu.Lock()
					reply := AppendEntriesResponse{
						Term:    -1,
						Success: false,
					}
					rf.mu.Unlock()
					peerReceivedHeartbeat := rf.peers[peerId].Call("Raft.AppendEntriesHandler", heartbeat, &reply)
					rf.mu.Lock()
					if peerReceivedHeartbeat && heartbeat.Term == rf.currentTerm && rf.role == 2 {
						//TODO
						rf.currentTerm = reply.Term
					}
					rf.mu.Unlock()
				}(peerId)
			}
		}
	}
}


```

No se si sea yo el que este mal o haya que en algún momento cambiar la propiedad de is running a true. Pero en nuestro código hasta el último commit de @sofimv (048ef56), no veo que esta propiedad se modifique o si hace falta modificarla en algún punto del código. 

No estoy seguro si el  __rf.running__ se refiere a si el server no esta muerto o si no esta corriendo para ser un leader... En el último commit que hice (b2f9f1b) modifique __rf.running__ a __rf.isRunningElection__ y si logré llegar a __AppendEntries__ y al parecer si se están haciendo correctamente los logs en esa parte pero todavía no logro llegar a el agreement. 

Lo que implementé diferente es agregue más atributos al heartbeat cuando hay un leader election, no estoy seguro si estoy bien y debe de ir ahí. Lo que estoy algo seguro es que debemos usar el AppendEntries en algún punto (Entendí del paper que cuando hubiera un nuevo Leader) y también cuando recibe un request del un cliente, pero no he podido llamar bien ```AppendEntries``` si lo anterior es cierto. 

Les comparto como se ve mi código:

```golang
func (rf *Raft) PromoteToLeader() {
	for range rf.heartBeatTicker.C { // deliver clock ticks at intervals
		if rf.isRunningElection || rf.role != 2 {
			break
		}

		// heartbeat := rf.craftHeartBeatMessage() //Upon election: send initial empty AppendEntries RPCs (heartbeat) to each server
		for peerId := range rf.peers {
			if peerId != rf.me {
				go func(peer int) {
					rf.mu.Lock()
					heartbeat := AppendEntriesArgs{
						Term:         rf.currentTerm,
						LeaderId:     rf.me,
						PrevLogIndex: rf.nextIndex[peerId] - 1,
						PrevLogTerm:  rf.log[rf.nextIndex[peerId - 1]].Term,
						LogEntries:   rf.log[rf.nextIndex[peerId - 1]:],
						LeaderCommit: rf.commitIndex,
					}
					reply := AppendEntriesResponse{}
					rf.mu.Unlock()
					peerReceivedHeartbeat := rf.peers[peerId - 1].Call("Raft.AppendEntriesHandler", heartbeat, &reply)
					rf.mu.Lock()
					if peerReceivedHeartbeat && heartbeat.Term == rf.currentTerm && rf.role == 2 {
						//TODO\
						rf.currentTerm = reply.Term

					}
					rf.mu.Unlock()
				}(peerId)
			}
		}
	}
}
```

también agregué un nuevo struct de tipo Log que según entendí es necesario para hacer que el código funcione en las nuevas funciones que todavía no habíamos implementado, como la de ```Start()```. 

```golang
// Add Log Structure, it should have a term and a command

type Log struct {
	Command interface{}
	Term    int
}

```

## Pasos para replicar.

Simplemente al correr el test de __testBasicAgree()__ en $../raft/test_test.go

## Info Adicional

Agregué también código en las funciones de ```Start()```  y en las dos funciones de Decodificar y Codificar el estado del server... Pero creo que es mejor mantener eso en otro issue. 

Gracias por su tiempo @charlieitesm @sofimv, espero sus comentarios, saludos!

**Comment by charlieitesm** [comment]
En qué branch está pasando esto @pepesrz91? Y a su vez en qué branch está basado?

**Comment by pepesrz91** [comment]
@charlieitesm es en el branch de [assignment3-sofia](https://github.com/mzareei/TC4003_assignment_Group_7/tree/assignment3-sofia). Creo que está basado en el último commit (ce64d0f) tuyo de [assignment3-charlie](https://github.com/mzareei/TC4003_assignment_Group_7/tree/assignment3-charlie/assignment3).
